In [2]:
import pandas as pd
dataset=pd.read_csv("cardio_dataset.csv").values
# load the dataset into a numpy array
print(dataset,dataset.shape)


[[  2.   48.  236.  ...   2.    0.    1.1]
 [  1.   48.  260.  ...   2.    1.    7. ]
 [  1.   44.  187.  ...   2.    0.    7. ]
 ...
 [  1.   65.  212.  ...   1.    0.   30.6]
 [  1.   66.  184.  ...   1.    0.   23.8]
 [  2.   45.  203.  ...   2.    0.    1. ]] (6644, 8)


In [3]:
data=dataset[:,0:7]
target=dataset[:,7]

In [4]:
from sklearn.model_selection import train_test_split
train_data,test_data,train_target,test_target=train_test_split(data,target,test_size=0.2)


In [5]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(train_data,train_target)

LinearRegression()

In [6]:
predicted_target=model.predict(test_data)

In [9]:
from sklearn.metrics import r2_score
r2=r2_score(test_target,predicted_target)
print("r2 score",r2)

r2 score 0.756451419179032


In [ ]:
# read about feature engineering and apply preprocessing to the dataset and try to improve the r2_score

In [10]:
import joblib 
joblib.dump(model,'regression-model-heart-risk.sav')

['regression-model-heart-risk.sav']